---
# Listen port
Port: 443

# HTTPS settings (Tls to false means HTTP)
Tls: true
PrivateKey: /opt/gfa/ssl/server.key
Certificate: /opt/gfa/ssl/server.crt

# Cookie and session configuration
#CookieDomain: "mydomain.com" # leave empty to disable sso
#CookieName: "_auth_gfa"
TokenExpire: 90 # jwt expiration delay in minutes
TokenRefresh: 2 # refresh jwt token if user make action in the last XX minutes (0 to disable refresh)

# template file for login/out
#HtmlFile: /opt/gfa/default.index.html

# key to sign jwt. If not provided, will be generated
#JwtSecretKey: "my_secret_key"

# number fo bcrypt iterations (default 10) (not used yet)
#HashCost: 10

# enable some debug output
#Debug: false

# list of users :
#   - key is the user id used for connexion
#   - values are :
#     - Id : the id used for connexion, must be the same as the key
#     - Name : The real name of User
#     - Password : is the bcrypt hash of the password (https://bcrypt.online/)
#     - IsAdmin : if true, all domains are allowed for this user (no check on AllowedDomains)
#     - AllowedDomains : list of strings, domains allowed for this user (if IsAdmin is false)
#Users:
#  - admin:
#      Id : admin
#      Name: ADMINISTRATEUR
#      Password: $2y$10$t6XPeRTf5.a.Gb3I/lYq7ukuOpx6fsJRstEXNfOP4jXjjGGZ2Af72 # pass
#      IsAdmin: true
#      AllowedDomains:
#  - toto:
#      Id: toto
#      Name: TOTO
#      Password: $2y$10$PpzVO0zStuQKJAHmdIBqQuagxkc732nnGR.Iet4SE5tJR1FjOuo.6 # pwd
#      IsAdmin: false
#      AllowedDomains: test.com
