---
# Listen port
Port: 8443

# HTTPS settings (Tls to false means HTTP)
Tls: true
PrivateKey: /opt/gfa/ssl/server.key
Certificate: /opt/gfa/ssl/server.crt

# Cookie and session configuration
#CookieDomain: "mydomain.com" # leave empty to disable sso
#CookieName: "_auth_gfa"
TokenExpire: 90 # jwt expiration delay in minutes
TokenRefresh: 2 # refresh jwt token if user make action in the last XX minutes (0 to disable refresh)

# template file for login/out
#HtmlFile: /opt/gfa/default.index.html

# key to sign jwt validate csrf. If not provided, will be generated. Must be >= 32bytes
#JwtSecretKey: "my_secret_JWT_key"
#CsrfSecretKey: "my_secret_CSRF_key"

# if this MagicIp is in JWT, it won't be tested against client's one
#MagicIp: "my_magic_ip"

# set log level
#LogLevel: info

# list of users :
#   - key is the username used for connexion, and the value passed by Remote-User Header
#   - values are :
#     - Password : is the bcrypt hash of the password (https://bcrypt.online/)
#     - AllowedDomains : list of regex for domains allowed for this user, use * for all
#Users:
#  - admin:
#      Password: $2y$10$t6XPeRTf5.a.Gb3I/lYq7ukuOpx6fsJRstEXNfOP4jXjjGGZ2Af72 # pass
#      AllowedDomains: ".*"
#  - jean:
#      Password: $2y$10$PpzVO0zStuQKJAHmdIBqQuagxkc732nnGR.Iet4SE5tJR1FjOuo.6 # pwd
#      AllowedDomains:
#        - "allowed.com"
#        - ".*website"

