---
# Listen port
Port: 443

# HTTPS settings (Tls to false means HTTP)
Tls: true
PrivateKey: /opt/gfa/ssl/server.key
Cert: /opt/gfa/ssl/server.crt

# Cookie and session configuration
CookieDomain: "" # leave empty to disable sso
CookieName: "_auth_gfa"
TokenExpire: 90 # jwt expiration delay minutes
TokenRefresh: 2 # refresh jwt token if user make action in the last XX minutes (0 to disable refresh)

# template file for login/out
HtmlFile: /opt/gfa/default.index.html

# key to sign jwt. If not provided, will be generated
JwtKey: ""

# number fo bcrypt iterations (default 10) (not used yet)
HashCost: 10

# enable some debug output
Debug: false

# list of users :
#   - key is the user name
#   - value is the bcrypt hash of the password (https://bcrypt.online/)
Users:
  - toto : "$2y$10$t6XPeRTf5.a.Gb3I/lYq7ukuOpx6fsJRstEXNfOP4jXjjGGZ2Af72" # pass
  - user : "$2y$10$PpzVO0zStuQKJAHmdIBqQuagxkc732nnGR.Iet4SE5tJR1FjOuo.6" # pwd
