---
Port: 9999
Tls: false
CookieDomain: "test_domain"
CookieName: "_test_gfa"
TokenExpire: 90
TokenRefresh: 2
HtmlFile: default.index.html
JwtSecretKey: "1111111111111111111111111111111111111111111111111111111111111111"
CsrfSecretKey: "22222222222222222222222222222222"
LogLevel: debug
Users:
  - admin:
      Password: $2y$10$t6XPeRTf5.a.Gb3I/lYq7ukuOpx6fsJRstEXNfOP4jXjjGGZ2Af72 # pass
      AllowedDomains: ".*"
  - jean:
      Password: $2y$10$PpzVO0zStuQKJAHmdIBqQuagxkc732nnGR.Iet4SE5tJR1FjOuo.6 # pwd
      AllowedDomains:
        - "allowed.com"
        - ".*website"
        - "url.net"
