name: Ci

on:
  push:
    branches: [ main, develop ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          quentinb69/go-forward-auth
        tags: |
          type=ref,event=branch,value={{branch}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
     - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - 
      name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}