name: Build multiarch image on tag

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract SCM informations
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - uses: actions/checkout@v3
    - name: Configuration of qemu for multiarch build
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Configure docker hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: docker/setup-buildx-action@v1
    - name: Build and push multiarch image on docker hub
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        push: true
        # tag image with :latest dans :<tag_version>
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-forward-auth:${{ steps.branch_name.outputs.SOURCE_TAG }},${{ secrets.DOCKER_HUB_USERNAME }}/go-forward-auth:latest
        #cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-forward-auth:buildcache
        #cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-forward-auth,mode=max
