name: Tests
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup Go
        uses: actions/setup-go@v2
      - 
        name: Tests
        uses: n8maninger/action-golang-test@v1